{% set name = "stracking" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sylvainprigent/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b69f937fa8895b2ed3c2095635e9307aa7ce5670940ed2c380d9986bb2c2dc0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - numpy
    - pip
    - python {{ python_min }}
    - scipy
  run:
    - numpy
    - python >={{ python_min }}
    - scikit-image >=0.18.1
    - scipy >=1.6.3

test:
  imports:
    - stracking
    - stracking.containers
    - stracking.data
    - stracking.detectors
    - stracking.features
    - stracking.filters
    - stracking.io
    - stracking.linkers
    - stracking.observers
    - stracking.properties
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sylvainprigent/stracking
  summary: Particles tracking for scientific imaging
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
